# version: '3.7'
# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: 'app'

#   redis:
#     image: redis:latest
#     command: redis-server --requirepass '${REDIS_PASSWORD}'

#   app:
#     build:
#       context: app
#     environment:
#       DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/app'
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
#       REDIS_PASSWORD: ${REDIS_PASSWORD}
#       SECRET_KEY: ${SECRET_KEY}
#     volumes:
#       - ./app:/app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db
#       - redis

version: '3'
services:
  app:
    build:
      context: app
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgresql://databaseuser:supersecretdbpassword@db:5432/app'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 'supersecretredispassword'
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'databaseuser'
      POSTGRES_PASSWORD: 'supersecretdbpassword'
      POSTGRES_DB: 'app'

  redis:
    image: redis:latest
    command: redis-server --requirepass 'supersecretredispassword'